kobayashi:
    analog:
        dane:
            cpu:    2200000000
            openmc: 1300000000
        tuolumne:
            cpu: 1350000000
            gpu: 0
        lassen:
            cpu: 300000000
            gpu: 0
    implicit_capture:
        dane:
            cpu: 297000000
        tuolumne:
            cpu: 162000000
            gpu: 0
        lassen:
            cpu: 45000000
            gpu: 0
